VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "starboard/ubuntu-arm64-20.04.5"
  config.vm.network "private_network", ip: "172.16.109.130"
  config.ssh.forward_agent = true

  config.vm.provider "vmware_desktop" do |v|
    v.gui = true
    v.linked_clone = false
    v.vmx["ethernet0.virtualdev"] = "vmxnet3"

    v.cpus = 2
    v.memory = "2048" # 2G
  end

  config.vm.synced_folder '.', '/home/vagrant/'
end
